encoding: utf-8
name: Anand Brahmbhatt
url: https://anand-10-prog.github.io/anand.github.io/
author:
  name: Anand Brahmbhatt
  email: anandbrahmbhatt27@gmail.com
description: Pre-Doctoral Researcher at Google AI.
permalink: /posts/:title/
include: ['_pages']
