encoding: utf-8
name: Shresth Verma
url: http://vermashresth.com
author:
  name: Shresth Verma
  email: vermashresth@gmail.com
description: Pre-Doctoral Researcher at Google AI.
permalink: /posts/:title/
include: ['_pages']
